FROM python:3.10-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app/ /app/app/
COPY ingestion/ /app/ingestion/
COPY .env /app/.env

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV FLASK_APP=app

# Set PYTHONPATH so Python can find the 'app' module
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

CMD ["python", "ingestion/ingest.py"]